app = 'recruitee-mcp-server'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "documents_data"
  destination = "/data"
  initial_size = "1gb"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
