[project]
name = "recruitee-mcp-server"
version = "0.1.0"
description = "MCP server for Recruitee API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "async-lru>=2.0.5",
    "fastmcp>=2.3.0",
]
